site_name: ARTA Docs (v0.1.3)
site_url: https://m-zakeri.github.io
repo_url: https://github.com/m-zakeri/ARTA
site_description: ARTA - Automatic Requirement Testability Analyzer
site_author: Morteza Zakeri
copyright: © 2020-2023 ARTA project - Morteza Zakeri Ph.D. thesis

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    logo: material/library
  features:
    - header.autohide
  extra:
    social:
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/mortazazakeri/

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
          setup_commands:
            - import sys
            - import os
          selection:
            members: True

nav:
    - Home: index.md
    - Dataset: dataset.md
    - Getting started:
        - Installation: getting_started/installation.md
        - Demo:  getting_started/demo.md
    - Publications: publications.md
    - Related projetcs: related_projects.md
    - Issue Tracker: 'https://github.com/m-zakeri/ARTA/issues'