# Generated by Django 3.0.7 on 2020-06-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('number', models.CharField(max_length=16, verbose_name='requirement id')),
                ('description', models.TextField(help_text='actual requirement', verbose_name='description')),
                ('requirement_type', models.CharField(choices=[('F', 'functional'), ('NF', 'non-functional')], max_length=2, verbose_name='type')),
                ('smells', models.TextField(blank=True, default='', verbose_name='smells')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('reviewed_date', models.DateTimeField(blank=True, null=True, verbose_name='reviewed date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='projects.Project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'requirement',
                'verbose_name_plural': 'requirements',
                'unique_together': {('project', 'number', 'title')},
            },
        ),
    ]
