# Generated by Django 3.0.7 on 2020-07-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_auto_20200614_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='smells',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='smells_count',
        ),
    ]
