# Generated by Django 3.0.7 on 2020-07-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_auto_20200706_2015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together=set(),
        ),
    ]
