# Generated by Django 3.0.7 on 2020-08-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0004_auto_20200713_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.CharField(choices=[('F', 'functional'), ('NF', 'non-functional')], default='F', max_length=2, verbose_name='type'),
        ),
    ]
