# Generated by Django 3.0.7 on 2020-08-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0005_auto_20200803_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='polarity',
            field=models.FloatField(default=0, verbose_name='polarity'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='score'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='subjectivity',
            field=models.FloatField(default=0, verbose_name='subjectivity'),
        ),
    ]
