# Generated by Django 3.0.7 on 2021-01-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0007_auto_20201020_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='testability',
            field=models.FloatField(default=0.0, verbose_name='testability'),
        ),
    ]
