# Generated by Django 3.0.7 on 2021-01-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0008_auto_20210119_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='readability',
            field=models.FloatField(default=0.0, verbose_name='readability'),
        ),
    ]
