# Generated by Django 3.0.7 on 2020-07-12 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requirements', '0004_auto_20200713_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='smell title')),
                ('description', models.CharField(max_length=512, verbose_name='smell description')),
            ],
            options={
                'verbose_name': 'smell',
                'verbose_name_plural': 'smells',
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_start', models.IntegerField(verbose_name='index start at')),
                ('index_stop', models.IntegerField(verbose_name='index stop at')),
                ('is_ok', models.BooleanField(default=False, verbose_name='is ok?')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('reviewed_date', models.DateTimeField(auto_now=True, verbose_name='reviewed date')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smells', to='requirements.Requirement', verbose_name='requirements')),
                ('smell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='detector.Smell', verbose_name='smell')),
            ],
            options={
                'verbose_name': 'finding',
                'verbose_name_plural': 'findings',
            },
        ),
    ]
