# Generated by Django 3.0.7 on 2020-07-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_smell_is_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='is added by hand?'),
        ),
    ]
