# Generated by Django 3.0.7 on 2020-07-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_finding_is_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smell',
            name='is_dictionary',
        ),
    ]
