# Generated by Django 3.0.7 on 2020-07-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_remove_smell_is_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='is reviewed?'),
        ),
    ]
