# Generated by Django 3.0.7 on 2020-07-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_finding_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='word',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='enter word'),
        ),
    ]
