# Generated by Django 3.0.7 on 2020-08-16 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0006_finding_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='smell',
            name='tip',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='tip'),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='word')),
                ('tip', models.CharField(blank=True, default='', max_length=512, verbose_name='tip')),
                ('smell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary', to='detector.Smell', verbose_name='smell')),
            ],
            options={
                'verbose_name': 'word',
                'verbose_name_plural': 'words',
                'unique_together': {('word', 'smell')},
            },
        ),
    ]
