# Generated by Django 3.0.7 on 2020-08-16 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0007_auto_20200816_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='word_dictionary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='detector.Word', verbose_name='dictionary member'),
        ),
        migrations.AlterField(
            model_name='word',
            name='tip',
            field=models.TextField(blank=True, default='', verbose_name='tip'),
        ),
    ]
